{"level": "DEBUG", "message": "debug message", "timestamp": "2024-09-23T14:50:28.511522+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 18, "threadname": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-09-23T14:50:28.511522+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 19, "threadname": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-09-23T14:50:28.511522+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 20, "threadname": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-09-23T14:50:28.513607+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 21, "threadname": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-09-23T14:50:28.514207+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 22, "threadname": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-09-23T14:50:28.514613+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 26, "threadname": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"e:\\Python\\ImportantConcepts\\modern_logging\\main.py\", line 24, in main\n    1/0\n    ~^~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-09-23T14:50:39.195986+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 18, "threadname": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-09-23T14:50:39.195986+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 19, "threadname": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-09-23T14:50:39.195986+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 20, "threadname": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-09-23T14:50:39.196987+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 21, "threadname": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-09-23T14:50:39.196987+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 22, "threadname": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-09-23T14:50:39.196987+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 26, "threadname": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"e:\\Python\\ImportantConcepts\\modern_logging\\main.py\", line 24, in main\n    1/0\n    ~^~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-09-23T14:59:12.813539+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 18, "threadname": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-09-23T14:59:12.813539+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 19, "threadname": "MainThread", "1": "lpm"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-09-23T14:59:12.813539+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 20, "threadname": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-09-23T14:59:12.814549+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 21, "threadname": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-09-23T14:59:12.814549+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 22, "threadname": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-09-23T14:59:12.814549+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 26, "threadname": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"e:\\Python\\ImportantConcepts\\modern_logging\\main.py\", line 24, in main\n    1/0\n    ~^~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-09-23T15:22:14.760725+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 18, "threadname": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-09-23T15:22:14.760725+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 19, "threadname": "MainThread", "1": "lpm"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-09-23T15:22:14.760725+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 20, "threadname": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-09-23T15:22:14.761768+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 21, "threadname": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-09-23T15:22:14.761768+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 22, "threadname": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-09-23T15:22:14.762728+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 26, "threadname": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"e:\\Python\\ImportantConcepts\\modern_logging\\main.py\", line 24, in main\n    1/0\n    ~^~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-09-23T15:22:22.868061+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 18, "threadname": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-09-23T15:22:22.868061+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 19, "threadname": "MainThread", "1": "lpm"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-09-23T15:22:22.868061+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 20, "threadname": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-09-23T15:22:22.868061+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 21, "threadname": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-09-23T15:22:22.869053+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 22, "threadname": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-09-23T15:22:22.869053+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 26, "threadname": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"e:\\Python\\ImportantConcepts\\modern_logging\\main.py\", line 24, in main\n    1/0\n    ~^~\nZeroDivisionError: division by zero"}
